language: node_js

node_js:
  - 6

sudo: required

services:
  - docker

  
before_install:
  - docker run -p 2379:2379 --env "ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379" --env "ETCD_ADVERTISE_CLIENT_URLS=http://localhost:2379" -d --name etcd quay.io/coreos/etcd
